[2025-03-12 02:31:45 +0000] [690] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/user
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fe910062710>
  on_reload: <function OnReload.on_reload at 0x7fe910062830>
  when_ready: <function WhenReady.when_ready at 0x7fe910062950>
  pre_fork: <function Prefork.pre_fork at 0x7fe910062a70>
  post_fork: <function Postfork.post_fork at 0x7fe910062b90>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fe910062cb0>
  worker_int: <function WorkerInt.worker_int at 0x7fe910062dd0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fe910062ef0>
  pre_exec: <function PreExec.pre_exec at 0x7fe910063010>
  pre_request: <function PreRequest.pre_request at 0x7fe910063130>
  post_request: <function PostRequest.post_request at 0x7fe9100631c0>
  child_exit: <function ChildExit.child_exit at 0x7fe9100632e0>
  worker_exit: <function WorkerExit.worker_exit at 0x7fe910063400>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fe910063520>
  on_exit: <function OnExit.on_exit at 0x7fe910063640>
  ssl_context: <function NewSSLContext.ssl_context at 0x7fe910063760>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2025-03-12 02:31:45 +0000] [690] [INFO] Starting gunicorn 23.0.0
[2025-03-12 02:31:45 +0000] [690] [DEBUG] Arbiter booted
[2025-03-12 02:31:45 +0000] [690] [INFO] Listening at: http://0.0.0.0:5000 (690)
[2025-03-12 02:31:45 +0000] [690] [INFO] Using worker: sync
[2025-03-12 02:31:45 +0000] [691] [INFO] Booting worker with pid: 691
[2025-03-12 02:31:45 +0000] [690] [DEBUG] 1 workers
[2025-03-12 02:31:45 +0000] [691] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/app.py", line 1, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
[2025-03-12 02:31:45 +0000] [691] [INFO] Worker exiting (pid: 691)
[2025-03-12 02:31:45 +0000] [690] [ERROR] Worker (pid:691) exited with code 3
[2025-03-12 02:31:45 +0000] [690] [ERROR] Shutting down: Master
[2025-03-12 02:31:45 +0000] [690] [ERROR] Reason: Worker failed to boot.
